### ISSUE TITLE
检测结果问题

### ISSUE THREAD

**Issue by renmystery** [Ayers-github/Chinese-License-Plate-Recognition#2]
大佬，我跑了一下检测结果汉字只有”京“，这个您测过了吗？555~

**Comment by Ayers-github** [comment]
你直接用的我的param文件和bin文件吗？

**Comment by Ayers-github** [comment]
这是我这边的输出结果：

单个车牌:川AM1560
所有车牌:川AM1560
川AM1560

**Comment by Ayers-github** [comment]
你点击branch，选择一下ncnn c++那个分支，里面有param文件

**Comment by renmystery** [comment]
![1667974819895](https://user-images.githubusercontent.com/50653514/200754389-59a713e5-db90-4060-9b30-3720980a9489.png)

按照您刚才的步骤，跑的结果

**Comment by Ayers-github** [comment]
已解决！
