### ISSUE TITLE
模型转换问题

### ISSUE THREAD

**Issue by shawn-AI-Tech** [Ayers-github/Chinese-License-Plate-Recognition#4]
大佬，模型转ncnn 的过程做了什么魔改吗，我在网上找了以下几个方案都没解决。能指点一下吗
1）直接用你的param，用自己转换出来的bin ，模型检测不出结果
2）在pytorch工程里修改export文件 加入training=torch.onnx.TrainingMode.TRAINING，依然会出slice unsupport问题。
3）改yolo.py 里的detect类，还是slice问题。

**Comment by Ayers-github** [comment]
我也还没解决，我那个模型不是v5face，是v5改的，参考的另外一个项目。你可以直接用我的转换好的检测模型，能正常跑。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月12日(周四) 中午11:56
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Ayers-github/Chinese-License-Plate-Recognition] 模型转换问题 (Issue #4)




 
大佬，模型转ncnn 的过程做了什么魔改吗，我在网上找了以下几个方案都没解决。能指点一下吗
 1）直接用你的param，用自己转换出来的bin ，模型检测不出结果
 2）在pytorch工程里修改export文件 加入training=torch.onnx.TrainingMode.TRAINING，依然会出slice unsupport问题。
 3）改yolo.py 里的detect类，还是slice问题。

**Comment by shawn-AI-Tech** [comment]
> 我也还没解决，我那个模型不是v5face，是v5改的，参考的另外一个项目。你可以直接用我的转换好的检测模型，能正常跑。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年1月12日(周四) 中午11:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [Ayers-github/Chinese-License-Plate-Recognition] 模型转换问题 (Issue #4) 大佬，模型转ncnn 的过程做了什么魔改吗，我在网上找了以下几个方案都没解决。能指点一下吗 1）直接用你的param，用自己转换出来的bin ，模型检测不出结果 2）在pytorch工程里修改export文件 加入training=torch.onnx.TrainingMode.TRAINING，依然会出slice unsupport问题。 3）改yolo.py 里的detect类，还是slice问题。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

能告知一下参考的哪个项目吗，我需要自己训练一个模型替进去

**Comment by Ayers-github** [comment]
https://github.com/zeusees/License-Plate-Detector 貌似是这个。我不太确定，有点久了

**Comment by shawn-AI-Tech** [comment]
> https://github.com/zeusees/License-Plate-Detector 貌似是这个。我不太确定，有点久了

好的，感谢你的帮助。我用这个工程转出ncnn模型，bin能用， param需要用你的。用转出的param还是会报错，我对比了一下层的index有些区别，后面我换yolov7face试试。

**Comment by Ayers-github** [comment]
不客气。7face应该也一样的。我试过。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月13日(周五) 上午9:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Ayers-github/Chinese-License-Plate-Recognition] 模型转换问题 (Issue #4)




  
https://github.com/zeusees/License-Plate-Detector 貌似是这个。我不太确定，有点久了
  
好的，感谢你的帮助。我用这个工程转出ncnn模型，bin能用， param需要用你的。用转出的param还是会报错，我对比了一下层的index有些区别，后面我换yolov7face试试。
