### ISSUE TITLE
您好，咱们车牌识别推理C++代码 crnn_rec函数中，是不是在遍历plate_mat时存在逻辑错误，识别出来的完全不争取？谢谢，期待您的回复。

### ISSUE THREAD

**Issue by tuodi** [Ayers-github/Chinese-License-Plate-Recognition#6]

**Comment by Ayers-github** [comment]
请参考安卓的jni中那边的代码。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Ayers-github/Chinese-License-Plate-Recognition"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月16日(星期四) 中午11:34
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Ayers-github/Chinese-License-Plate-Recognition] 您好，咱们车牌识别推理C++代码 crnn_rec函数中，是不是在遍历plate_mat时存在逻辑错误，识别出来的完全不争取？谢谢，期待您的回复。 (Issue #6)
