### ISSUE TITLE
更换自己训练的识别模型

### ISSUE THREAD

**Issue by maikelaolin** [Ayers-github/Chinese-License-Plate-Recognition#8]
你好我想把识别模型更换为自己的，我更换后只显示车牌的颜色，无法识别到车牌的内容，应该如何修改。期待您的回信，多谢多谢

**Comment by Ayers-github** [comment]
请修改app
/src
/main
/jni
/yolov5ncnn_jnitest.cpp
中static vector<string> crnn_rec(const cv::Mat& bgr)车牌识别后处理代码。改成你自己的后处理逻辑
